# Streamlit Cloud나 로컬 .streamlit/secrets.toml 에 저장
SHEET_ID = "1pwvGq2KaACiRXEC70Rtnc2VAlB5AGErUUPTFB00G2H0"         # 예: https://docs.google.com/spreadsheets/d/<이부분>/edit
SHEET_NAME = "Form Responses 1"          # 시트 탭 이름
GSHEETS_CREDENTIALS = "streamlit-dashboard@main-shade-231707.iam.gserviceaccount.com"
TIMEZONE = "Asia/Seoul"
